version: 1.0.{build}

environment:
  global:
    PLATFORMTOOLSET: "v140"
  matrix:
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: Win32
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MinGW
      PLATFORM: Win32
    - BUILD_TYPE: Release
      COMPILER: MinGW
      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w64
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MinGW-w64
      PLATFORM: x64

build_script:
  - md build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - cd build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - if [%COMPILER%]==[MinGW] set PATH=C:\MinGW\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=SDL-Mixer-X -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES ..
  - if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=SDL-Mixer-X -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES ..
  - if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=SDL-Mixer-X -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES ..
  - if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=SDL-Mixer-X -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES ..
  - if [%COMPILER%]==[MinGW] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER%]==[MinGW] mingw32-make install
  - if [%COMPILER%]==[MinGW-w64] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER%]==[MinGW-w64] mingw32-make install
  - if [%COMPILER%]==[MSVC15] cmake --build . --config %BUILD_TYPE% --target install
  - 7z a -t7z -mx9 "SDL-Mixer-X-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z" "SDL-Mixer-X"
  - move SDL-Mixer-X-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z ..

artifacts:
  - path: 'SDL-Mixer-X-*.7z'

deploy:
  - provider: Environment
    name: WohlnetFTP

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

