version: 2.x.{build}

environment:
  global:
    PLATFORMTOOLSET: "v140"
  matrix:
    - BUILD_TYPE: MinSizeRel
      COMPILER: MinGW-w32
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32-VB6-Binding
      IS_VB6_BINDING: YES
      EXTRA_CMAKE_FLAGS: "-DBUILD_AS_VB6_BINDING=ON -DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.12 -DAUDIO_CODECS_SDL2_GIT_BRANCH=983bbf9 -DWITH_SDL2_WASAPI=OFF"
    - BUILD_TYPE: MinSizeRel
      COMPILER: MinGW-w32
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32-VB6-Binding-SDL-2.0.8
      IS_VB6_BINDING: YES
      EXTRA_CMAKE_FLAGS: "-DBUILD_AS_VB6_BINDING=ON -DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.8 -DAUDIO_CODECS_SDL2_GIT_BRANCH=e9fc66a -DWITH_SDL2_WASAPI=OFF"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32-SDL-2.0.12-DS
      PLATFORMTOOLSET: "v140_xp"
      EXTRA_CMAKE_FLAGS: "-DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.12 -DAUDIO_CODECS_SDL2_GIT_BRANCH=983bbf9 -DWITH_SDL2_WASAPI=OFF"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32-SDL-2.0.12
      PLATFORMTOOLSET: "v140_xp"
      EXTRA_CMAKE_FLAGS: "-DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.12 -DAUDIO_CODECS_SDL2_GIT_BRANCH=983bbf9"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32-SDL-2.0.10-DS
      PLATFORMTOOLSET: "v140_xp"
      EXTRA_CMAKE_FLAGS: "-DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.10 -DAUDIO_CODECS_SDL2_GIT_BRANCH=0e9560a -DWITH_SDL2_WASAPI=OFF"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32-SDL-2.0.10
      PLATFORMTOOLSET: "v140_xp"
      EXTRA_CMAKE_FLAGS: "-DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.10 -DAUDIO_CODECS_SDL2_GIT_BRANCH=0e9560a"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32-SDL-2.0.9-DS
      PLATFORMTOOLSET: "v140_xp"
      EXTRA_CMAKE_FLAGS: "-DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.9 -DAUDIO_CODECS_SDL2_GIT_BRANCH=c49ecf6 -DWITH_SDL2_WASAPI=OFF"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32-SDL-2.0.9
      PLATFORMTOOLSET: "v140_xp"
      EXTRA_CMAKE_FLAGS: "-DAUDIO_CODECS_SDL2_HG_BRANCH=release-2.0.9 -DAUDIO_CODECS_SDL2_GIT_BRANCH=c49ecf6"
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w32
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
    - BUILD_TYPE: Release
      COMPILER: MinGW-w32
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w64
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MinGW-w64
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v141_xp"

    - BUILD_TYPE: Debug
      COMPILER: MSVC19
      COMPILER_FAMILY: MSVC2
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: x64
      PLATFORMTOOLSET: "v142"
    - BUILD_TYPE: Release
      COMPILER: MSVC19
      COMPILER_FAMILY: MSVC2
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: x64
      PLATFORMTOOLSET: "v142"
    - BUILD_TYPE: Debug
      COMPILER: MSVC19
      COMPILER_FAMILY: MSVC2
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v142"
    - BUILD_TYPE: Release
      COMPILER: MSVC19
      COMPILER_FAMILY: MSVC2
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v142"

build_script:
  - md build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - cd build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - if [%COMPILER%]==[MinGW] set PATH=C:\MinGW\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w32] set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if NOT [%COMPILER_FAMILY%]==[MSVC2] cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=SDL-Mixer-X -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES %EXTRA_CMAKE_FLAGS% ..
  - if [%COMPILER_FAMILY%]==[MSVC2] cmake -G "%GENERATOR%" -A %PLATFORM% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=SDL-Mixer-X -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES %EXTRA_CMAKE_FLAGS% ..
  - if [%COMPILER_FAMILY%]==[MinGW] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER_FAMILY%]==[MinGW] mingw32-make install
  - if [%COMPILER_FAMILY%]==[MSVC] cmake --build . --config %BUILD_TYPE% --target install
  - if [%COMPILER_FAMILY%]==[MSVC2] cmake --build . --config %BUILD_TYPE% --target install
  - if NOT [%IS_VB6_BINDING%]==[YES] 7z a -t7z -mx9 "SDL-Mixer-X-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z" "SDL-Mixer-X"
  - if [%IS_VB6_BINDING%]==[YES] 7z x ../VB6_Wrapper/SDL_Mixer_vb6_example.clean.7z * -osdl-mixer-vb6
  - if [%IS_VB6_BINDING%]==[YES] copy ..\VB6_Wrapper\ReadME.txt sdl-mixer-vb6
  - if [%IS_VB6_BINDING%]==[YES] copy ..\SDL2_mixer_ext.License.txt sdl-mixer-vb6\licenses\SDL2MixerVB.License.txt
  - if [%IS_VB6_BINDING%]==[YES] copy ..\docs\SDL_mixer_ext.html sdl-mixer-vb6\
  - if [%IS_VB6_BINDING%]==[YES] 7z a -t7z -mx9 "SDL-Mixer-X-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z" "sdl-mixer-vb6/*"
  - move SDL-Mixer-X-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z ..

artifacts:
  - path: 'SDL-Mixer-X-$(COMPILER)-$(BUILD_TYPE)-$(PLATFORM).7z'

deploy:
  - provider: Environment
    name: WohlnetFTP

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
